version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SAMPLE-ENV"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jerv9d01rrhd"
s3_prefix = "SAMPLE-ENV"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"staging\""
